export const LEAGUE_LOGOS: Record<string, string> = {
  'premier-league': '/leagues/premier-league.svg',
  'la-liga': '/leagues/la-liga.png',
  'bundesliga': '/leagues/bundesliga.svg',
  'serie-a': '/leagues/serie-a.png?v=2',
  'ligue-1': '/leagues/ligue-1.png?v=2',
  'liga-portugal': '/leagues/liga-portugal.png?v=2',
  'eredivisie': '/leagues/eredivisie.png?v=5',
  'europa-andere': '/leagues/europa-andere.svg',
  'nationalmannschaften': '/leagues/nationalteams-europe.png',
  'brasileirao': '/leagues/brasileirao.png',
  'liga-argentina': '/leagues/liga-argentina.png',
  'mls': '/leagues/mls.png',
  'liga-mx': '/leagues/liga-mx.png',
  'saudi-pro-league': '/leagues/saudi-pro-league.png',
  'primera-chile': '/leagues/primera-chile.png',
  'zweitligisten': '/leagues/zweitligisten.svg',
  'clubs-world': '/leagues/clubs-world.svg',
  'nationalteams-europe': '/leagues/nationalteams-europe.png',
  'nationalteams-world': '/leagues/nationalteams-world.svg',
};
