export const LEAGUE_LOGOS: Record<string, string> = {
  'premier-league': '/leagues/premier-league.svg',
  'la-liga': '/leagues/la-liga.svg',
  'bundesliga': '/leagues/bundesliga.svg',
  'serie-a': '/leagues/serie-a.svg',
  'ligue-1': '/leagues/ligue-1.png',
  'liga-portugal': '/leagues/liga-portugal.png',
  'eredivisie': '/leagues/eredivisie.png',
  'scottish-premiership': '/leagues/scottish-premiership.png',
  'efl-championship': '/leagues/efl-championship.png',
  'super-lig': '/leagues/super-lig.png',
  'super-league-greece': '/leagues/super-league-greece.png',
  'hnl': '/leagues/hnl.png',
  'liga-1-romania': '/leagues/liga-1-romania.png',
  'europa-andere': '/leagues/europa-andere.svg',
  'nationalteams-europe': '/leagues/nationalteams-europe.png',
  'nationalteams-world': '/leagues/nationalteams-world.svg',
  'clubs-world': '/leagues/clubs-world.svg',
};
