export const SUB_LEAGUE_SLUGS: Record<string, string> = {
  'Süper Lig': 'super-lig',
  'Super League Greece': 'super-league-greece',
  'Österreichische Bundesliga': 'osterreichische-bundesliga',
  'League of Ireland': 'league-of-ireland',
  'Hrvatska Nogometna Liga': 'hrvatska-nogometna-liga',
  'Liga I': 'liga-i',
  'Allsvenskan': 'allsvenskan',
  'Superliga': 'superliga',
  'Jupiler Pro League': 'jupiler-pro-league',
  'Super League': 'super-league',
  'Brasileirão': 'brasileirao',
  'Liga Profesional': 'liga-argentina',
  'MLS': 'mls',
  'Liga MX': 'liga-mx',
  'Saudi Pro League': 'saudi-pro-league',
  'Primera División': 'primera-chile',
};

export const SUB_LEAGUE_LOGOS: Record<string, string> = {
  'super-lig': '/leagues/super-lig.png',
  'super-league-greece': '/leagues/super-league-greece.png',
  'osterreichische-bundesliga': '/leagues/austrian-bundesliga.png',
  'league-of-ireland': '/leagues/league-of-ireland.png',
  'hrvatska-nogometna-liga': '/leagues/hnl.png',
  'liga-i': '/leagues/liga-1-romania.png',
  'allsvenskan': '/leagues/allsvenskan.png',
  'superliga': '/leagues/superliga-denmark.png',
  'jupiler-pro-league': '/leagues/jupiler-pro-league.png',
  'super-league': '/leagues/super-league-switzerland.png',
  'brasileirao': '/leagues/brasileirao.png',
  'liga-argentina': '/leagues/liga-argentina.png',
  'mls': '/leagues/mls.png',
  'liga-mx': '/leagues/liga-mx.png',
  'saudi-pro-league': '/leagues/saudi-pro-league.png',
  'primera-chile': '/leagues/primera-chile.png',
};
