export const SUB_LEAGUE_SLUGS: Record<string, string> = {
  'Süper Lig': 'super-lig',
  'Super League Greece': 'super-league-greece',
  'Österreichische Bundesliga': 'osterreichische-bundesliga',
  'League of Ireland': 'league-of-ireland',
  'Hrvatska Nogometna Liga': 'hrvatska-nogometna-liga',
  'Liga I': 'liga-i',
  'Allsvenskan': 'allsvenskan',
  'Superliga': 'superliga',
  'Jupiler Pro League': 'jupiler-pro-league',
  'Super League': 'super-league',
  'Brasileirão': 'brasileirao',
  'Liga Profesional': 'liga-argentina',
  'MLS': 'mls',
  'Liga MX': 'liga-mx',
  'Saudi Pro League': 'saudi-pro-league',
  'Primera División': 'primera-chile',
  'Europa': 'europa',
  'Südamerika': 'suedamerika',
  'Nordamerika': 'nordamerika',
  'Afrika': 'afrika',
  'Asien': 'asien',
  'EFL Championship': 'efl-championship',
  'Segunda División': 'segunda-division',
  '2. Bundesliga': '2-bundesliga',
  'Serie B': 'serie-b',
  'Ligue 2': 'ligue-2',
  'Scottish Premiership': 'scottish-premiership',
};

export const SUB_LEAGUE_COUNTRIES: Record<string, string> = {
  'Süper Lig': 'Türkei',
  'Super League Greece': 'Griechenland',
  'Österreichische Bundesliga': 'Österreich',
  'League of Ireland': 'Irland',
  'Hrvatska Nogometna Liga': 'Kroatien',
  'Liga I': 'Rumänien',
  'Allsvenskan': 'Schweden',
  'Superliga': 'Dänemark',
  'Jupiler Pro League': 'Belgien',
  'Super League': 'Schweiz',
  'EFL Championship': 'England',
  'Segunda División': 'Spanien',
  '2. Bundesliga': 'Deutschland',
  'Serie B': 'Italien',
  'Ligue 2': 'Frankreich',
  'Scottish Premiership': 'Schottland',
  'Brasileirão': 'Brasilien',
  'Liga Profesional': 'Argentinien',
  'MLS': 'USA / Kanada',
  'Liga MX': 'Mexiko',
  'Saudi Pro League': 'Saudi-Arabien',
  'Primera División': 'Chile',
};

export const SUB_LEAGUE_LOGOS: Record<string, string> = {
  'super-lig': '/leagues/super-lig.png',
  'super-league-greece': '/leagues/super-league-greece.png',
  'osterreichische-bundesliga': '/leagues/austrian-bundesliga.png',
  'league-of-ireland': '/leagues/league-of-ireland.png',
  'hrvatska-nogometna-liga': '/leagues/hnl.png',
  'liga-i': '/leagues/liga-1-romania.png',
  'allsvenskan': '/leagues/allsvenskan.png',
  'superliga': '/leagues/superliga-denmark.png',
  'jupiler-pro-league': '/leagues/jupiler-pro-league.png',
  'super-league': '/leagues/super-league-switzerland.png',
  'brasileirao': '/leagues/brasileirao.png',
  'liga-argentina': '/leagues/liga-argentina.png',
  'mls': '/leagues/mls.png',
  'liga-mx': '/leagues/liga-mx.png',
  'saudi-pro-league': '/leagues/saudi-pro-league.png',
  'primera-chile': '/leagues/primera-chile.png',
  'europa': '/leagues/continent-europa.svg?v=2',
  'suedamerika': '/leagues/continent-suedamerika.svg?v=2',
  'nordamerika': '/leagues/continent-nordamerika.svg?v=2',
  'afrika': '/leagues/continent-afrika.svg?v=2',
  'asien': '/leagues/continent-asien.svg?v=2',
  'efl-championship': '/leagues/efl-championship.png',
  'segunda-division': '/leagues/segunda-division.png',
  '2-bundesliga': '/leagues/2-bundesliga.png',
  'serie-b': '/leagues/serie-b.png',
  'ligue-2': '/leagues/ligue-2.png',
  'scottish-premiership': '/leagues/scottish-premiership.png',
};
